AgileManagement.Mvc/Controllers/ProjectController.cs
using AgileManagement.Application;
using AgileManagement.Domain;
using AgileManagement.Mvc.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgileManagement.Mvc.Controllers
{
    public class ProjectController : AuthBaseController
    {
        private readonly IProjectWithContributorsRequestService _projectWithContributorsRequestService;
        private readonly IContributorProjectAccessApprovementService _contributorProjectAccessApprovementService;
        private readonly IConributorProjectList _conributorProjectList;
    



        public ProjectController(AuthenticatedUser authenticatedUser, IProjectWithContributorsRequestService projectWithContributorsRequestService, IContributorProjectAccessApprovementService contributorProjectAccessApprovementService, IProjectRepository projectRepository, IConributorProjectList conributorProjectList) : base(authenticatedUser)
        {
            _projectWithContributorsRequestService = projectWithContributorsRequestService;
            _contributorProjectAccessApprovementService = contributorProjectAccessApprovementService;
            _conributorProjectList = conributorProjectList;
        }

        public IActionResult Home()
        {
            var response=_conributorProjectList.OnProcess(authUser.UserId);

            return View(response);
        }

        public IActionResult ApprovedProject(string projectId)
        {
            // burada bu projenin contributor'ı olup olmadığını kontrol ederiz.
            // ona göre proje detaylarını göreceğimiz sayfa gelir.

            var request = new ProjectWithContributorRequestDto
            {
                ProjectId = projectId
            };


            var response = _projectWithContributorsRequestService.OnProcess(request);


            if (response.Projects.Count() > 0)
            {
                if (!response.Projects[0].Contributors.Any(x => x.UserId == authUser.UserId))
                {
                    return Unauthorized();
                }
                else
                {
                    return View(response.Projects[0]);
                }
            }

            return View();
        }

        /// <summary>
        /// İlgili Projede ilgili contributor'a erim izni verir.
        /// </summary>
        /// <param name="projectId"></param>
        /// <param name="userId"></param>
        /// <param name="accepted"></param>
        /// <returns></returns>
        public IActionResult ContributorProjectApprove(string projectId, string userId, bool accepted)
        {
            var request = new ContributorProjectAccessApprovementDto
            {
                ProjectId = projectId,
                UserId = userId,
                Approve = accepted
            };

            var approved = _contributorProjectAccessApprovementService.OnProcess(request);

            ViewBag.Message = approved ? "Projeye erişimizi var" : "Proje erimi red edildi";
            ViewBag.Status = approved;
            ViewBag.ProjectId = projectId;


            return View();
        }
        
    }
}

AgileManagement.Mvc/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgileManagement.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark text-white border-bottom box-shadow mb-3">

            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgileManagement.Mvc</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex">
                <ul class="navbar-nav flex-grow-1 justify-content-end">

                    @if (User.Identity.IsAuthenticated)
                    {



                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Project" asp-action="Management">My Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Project" asp-action="Create">New Project</a>
                        </li>
}


                    @if (!User.Identity.IsAuthenticated)
                    {



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Oturum Aç</a>
                        </li>
 }
                    else
                    {

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span>@User.Identity.Name</span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Oturumu kapat</a>
                            </div>
                        </li>
}

                </ul>
            </div>

        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AgileManagement.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>